# Site settings
title: CuraDerme | Sua saúde é nossa prioridade!
description: "Consultório de Enfermagem."
baseurl: "" # the subpath of your site, e.g. /blog
url: "curadermesi.com.br" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Curaderme
    hero_description: Sua saúde é nossa prioridade!

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 3621-3213
    emergency: 9.9664-3110 / 9.8220-1412
    email: curadermesi@hotmail.com
    address: Av. Martins Viêira, 408, Santana do Ipanema

# Opening hours
monday: 15:00 – 18:00
tuesday-friday: 08:00 - 12:00 / 15:00 - 18:00
saturday: 08:00 - 12:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Av. Martins Viêira, 408, Santana do Ipanema - AL, 57500-000
    address_details: svg/min/logo.svg

# Social settings
facebook: 
twitter: 
instagram: http://instagram.com/curadermesi
youtube: 
skype: 
feed: no

# Footer
copyright: © 2019 CuraDerme - Todos os direitos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
